# Generated by Django 4.2.4 on 2023-08-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=100)),
                ('cron_schedule', models.CharField(max_length=25)),
                ('created_at', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
