# Generated by Django 4.2.4 on 2023-09-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
