# Generated by Django 4.2.4 on 2023-09-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_jobs_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('email_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
