# Generated by Django 4.2.4 on 2023-09-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_accounts_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_verified',
            field=models.IntegerField(default=0),
        ),
    ]
